name: Check Branch Name Formatting
on:
  pull_request:
    branches:
      - staging
      - develop

jobs:
  build:
    name: Check Branch Name Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checking the branch name to make sure it conforms to our branch standards.
      env:
        BRANCH: ${{ github.event.pull_request.head.ref }}
      uses: parkhub/check-branch-name-action@master