name: Create Official Release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create Official Release
    runs-on: ubuntu-latest
    steps:
    - name: Creating an official release for this application version.
      env:
        RELEASE_TYPE: "patch"
        USERNAME: Fliko
        TOKEN: ${{ github.token }}
        REPO: ${{ github.repository }}
      uses: Fliko/create-official-release-action@master